steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=MODEL_GCS_PATH=${_MODEL_GCS_PATH}
      - --tag=${_IMAGE_URI}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

images:
  - ${_IMAGE_URI}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_URI: us-central1-docker.pkg.dev/${PROJECT_ID}/ml-images/support-classifier:latest
  _MODEL_GCS_PATH: gs://${PROJECT_ID}-models/banking77-distilbert
